apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: bench-disk-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bench-disk-deployment
    spec:
      containers:
      - name: bench-disk-deployment
        image: ubuntu:latest
        command: ["tail", "-f", "/var/log/message", " ", ">" ," ", "/dev/null"]
        volumeMounts:
        - mountPath: "/test-ssd/"
          name: "ssd375"
      volumes:
      - name: "ssd375"
        hostPath:
          path: "/mnt/disks/ssd0"
