apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: benchmark-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: benchmark-deployment
    spec:
      containers:
      - name: benchmark
        image: exactfunctor/sysbench
        command: ["sleep", "9999"]
